language: android
dist: trusty
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

android:
  components:
    - tools
    - platform-tools

    # The BuildTools version
    - build-tools-28.0.3

    # The SDK version
    - android-28

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-28

before_install:
  - yes | sdkmanager "platform-tools" > /dev/null
  - yes | sdkmanager "build-tools;28.0.3" > /dev/null
  - yes | sdkmanager "platforms;android-28" > /dev/null
  - yes | sdkmanager "extras;google;m2repository" > /dev/null
  - yes | sdkmanager "extras;android;m2repository" > /dev/null

before_script:
  - chmod +x gradlew

script:
  - ./gradlew assembleRelease -PdisablePreDex

deploy:
  provider: script
  script: ./gradlew clean build bintrayUpload -PdryRun=false
  skip_cleanup: true # to upload artifacts created during the build
  dry-run: false
  on:
    branch: master

